// Docs sidebar, by slug under /docs/. scripts/sync-docs.mjs fails the build
// when a page in ../docs is missing here.
export const sidebar = [
  { label: 'Start', items: ['docs', 'docs/configuration'] },
  {
    label: 'Use',
    items: [
      'docs/usage/recording-modes',
      'docs/usage/hotkeys',
      'docs/usage/paste',
      'docs/usage/text-processing',
      'docs/usage/audio-input',
      'docs/usage/feedback',
      'docs/usage/cli',
    ],
  },
  {
    label: 'Backends',
    items: [
      'docs/backends/overview',
      'docs/backends/memory',
      'docs/backends/language',
      'docs/backends/cohere-transcribe',
      'docs/backends/parakeet',
      'docs/backends/faster-whisper',
      'docs/backends/whisper-cpp',
      { slug: 'docs/backends/parakeet-cpp', badge: 'experimental' },
      { slug: 'docs/backends/qwen3-asr', badge: 'experimental' },
      'docs/backends/rest-api',
      'docs/backends/realtime-websocket',
    ],
  },
  {
    label: 'Integrations',
    items: ['docs/integrations/waybar', 'docs/integrations/noctalia', 'docs/integrations/desktops'],
  },
  {
    label: 'Maintain',
    items: [
      'docs/managed-installation',
      'docs/troubleshooting',
      { label: 'Benchmarks', collapsed: true, items: [{ autogenerate: { directory: 'docs/benchmarks' } }] },
    ],
  },
];

// Slugs the sidebar reaches, autogenerated directories as prefixes.
export function sidebarSlugs(items = sidebar, out = { pages: new Set(), dirs: [] }) {
  for (const item of items) {
    if (typeof item === 'string') out.pages.add(item);
    else if (item.slug) out.pages.add(item.slug);
    else if (item.autogenerate) out.dirs.push(item.autogenerate.directory + '/');
    else if (item.items) sidebarSlugs(item.items, out);
  }
  return out;
}
